# ALL UNITS ARE IN AGENT BODY LENGTHS UNLESS OTHERWISE SPECIFIED
type: "Goalbot"
sensors:
  custom_state_decision: "Linear"
  sensors:
    - type: "BinaryFOVSensor"
      theta: 0.45   # Vision Angle / 2 (Radians)
      degrees: false
      agent_sensing_range: 1.0 # meters. previously 2.55
      show: true
      goal_sensing_range: 1.0
      use_goal_state: true
      wall_sensing_range: 1.0
      fn: 0.00  # 0.10
      fp: 0.00  # 0.05
      bias: 0
      store_history: false
      seed: 10
controller:
  - 0
  - 0
  - 0
  - 0
agent_radius: 0.1
stop_at_goal: false
dt: 0.025
body_color:
  - 255
  - 0
  - 0
body_filled: true