---
type: "RectangularWorld"
size:  # in meters
  - 10
  - 10
# n_agents: 10
# init_type:
#   type: "RectRandomInit"  # A starting region where agents will spawn at t=0
#   bb:
#     - - 3.4 # X (m) Upper Left Bounding Box Corner
#       - 3.4 # Y
#     - - 4.6 # X (m) Lower Right Bounding Box Corner
#       - 4.6 # Y
#   seed: 2023 # ADD SEED HERE TO ENSURE SAME INITIALIZATION EVERY TIME
agents:
  - type: "MazeAgent"
    position: [4, 4]
    agent_radius: 0.15
    controller:
      type: "StaticController"
      output: [0.001, 0.001]
    angle: 0
  # - type: "StaticAgent"
  #   position: [2, 2]
  #   agent_radius: 0.5
  #   angle: PI
padding: 0
collide_walls: false  # Use No Environment Walls for this problem
show_walls: false  # Hide Default Walls,
metadata:
  hash: _hash
stop_at: 1000000 # Upper Simulation Limit (timesteps)
